name: deploy

on:
  # Trigger the workflow on push to main branch
  push:
    branches:
      - main

jobs:
  build-and-deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.AIML_COMMON_CICD_TOKEN }}
      - name: Cache apt packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
            packages: curl git-lfs ffmpeg libsm6 libxext6 graphviz libgraphviz-dev xdg-utils swig gringo  libgraphviz-dev libsndfile1-dev xdg-utils swig gringo gobject-introspection libcairo2-dev libgirepository1.0-dev pkg-config python3-dev python3-gi
            version: 1.0
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # caching pip dependencies
      - run: pip install -r requirements.txt
     
      - name: Build the book
        shell: bash -l {0}
        run: |
          jupyter-book build  data_mining

    # Deploy the book's HTML to gh-pages branch
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: data_mining/_build/html    
          
